/*
 * Employee Profiles API
 *
 * Employee profiles of hospital staff for the Web-In-Cloud system
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance

import (
	"github.com/gin-gonic/gin"
)

type EmployeeProfilesAPI interface {

	// ArchiveEmployeeProfile Delete /api/employees/:employeeId
	// Archive an employee profile
	ArchiveEmployeeProfile(c *gin.Context)

	// CreateEmployeeProfile Post /api/employees
	// Create a new employee profile
	CreateEmployeeProfile(c *gin.Context)

	// GetEmployeeProfile Get /api/employees/:employeeId
	// Get a single employee profile by id
	GetEmployeeProfile(c *gin.Context)

	// ListEmployeeProfiles Get /api/employees
	// List employee profiles
	ListEmployeeProfiles(c *gin.Context)

	// UpdateEmployeeProfile Put /api/employees/:employeeId
	// Update an existing employee profile
	UpdateEmployeeProfile(c *gin.Context)
}
