/*
 * Performance Records API
 *
 * Performance records of hospital staff (worked hours, examinations, operations, on-call shifts) for the Web-In-Cloud system
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance

import (
	"github.com/gin-gonic/gin"
)

type PerformanceRecordsAPI interface {


    // CreatePerformanceRecord Post /api/performance-records
    // Create a new performance record 
     CreatePerformanceRecord(c *gin.Context)

    // DeletePerformanceRecord Delete /api/performance-records/:recordId
    // Delete (archive) a performance record 
     DeletePerformanceRecord(c *gin.Context)

    // GetPerformanceRecord Get /api/performance-records/:recordId
    // Get a single performance record by id 
     GetPerformanceRecord(c *gin.Context)

    // ListPerformanceRecords Get /api/performance-records
    // List performance records 
     ListPerformanceRecords(c *gin.Context)

    // UpdatePerformanceRecord Put /api/performance-records/:recordId
    // Update an existing performance record 
     UpdatePerformanceRecord(c *gin.Context)

}