/*
 * Department Assignments API
 *
 * Department assignments of hospital staff (assignment of employees to ambulances and hospital departments) for the Web-In-Cloud system
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance

import (
	"github.com/gin-gonic/gin"
)

type DepartmentAssignmentsAPI interface {

	// CreateDepartmentAssignment Post /api/department-assignments
	// Create a new department assignment
	CreateDepartmentAssignment(c *gin.Context)

	// DeleteDepartmentAssignment Delete /api/department-assignments/:assignmentId
	// Delete (revoke) a department assignment
	DeleteDepartmentAssignment(c *gin.Context)

	// GetDepartmentAssignment Get /api/department-assignments/:assignmentId
	// Get a single department assignment by id
	GetDepartmentAssignment(c *gin.Context)

	// ListDepartmentAssignments Get /api/department-assignments
	// List department assignments
	ListDepartmentAssignments(c *gin.Context)

	// UpdateDepartmentAssignment Put /api/department-assignments/:assignmentId
	// Update an existing department assignment
	UpdateDepartmentAssignment(c *gin.Context)
}
