/*
 * Employee Profiles API
 *
 * Employee profiles of hospital staff for the Web-In-Cloud system
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance

type EmployeeStatus string

// List of EmployeeStatus
const (
	ACTIVE   EmployeeStatus = "active"
	ARCHIVED EmployeeStatus = "archived"
)
