/*
 * Department Assignments API
 *
 * Department assignments of hospital staff (assignment of employees to ambulances and hospital departments) for the Web-In-Cloud system
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance

type DepartmentAssignment struct {

	// Server-assigned unique identifier
	Id int64 `json:"id,omitempty"`

	// Employee identifier (badge or HR id)
	EmployeeId string `json:"employeeId,omitempty"`

	// Full name of the employee
	EmployeeName string `json:"employeeName"`

	// Department identifier
	DepartmentId string `json:"departmentId,omitempty"`

	// Human-readable department / ambulance name
	DepartmentName string `json:"departmentName"`

	// Role of the employee within the department
	Role string `json:"role,omitempty"`

	// First day of the assignment (ISO 8601)
	FromDate string `json:"fromDate"`

	// Last day of the assignment (ISO 8601). Empty means the assignment is currently active.
	ToDate string `json:"toDate,omitempty"`

	// Optional free-text note
	Note string `json:"note,omitempty"`
}
