/*
 * Performance Records API
 *
 * Performance records of hospital staff (worked hours, examinations, operations, on-call shifts) for the Web-In-Cloud system
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance

type PerformanceRecord struct {

	// Server-assigned unique identifier
	Id int64 `json:"id,omitempty"`

	// Employee identifier (badge or HR id)
	EmployeeId string `json:"employeeId,omitempty"`

	// Full name of the employee
	EmployeeName string `json:"employeeName"`

	// Date the work was performed (ISO 8601)
	Date string `json:"date"`

	// Hours worked on this date
	HoursWorked float32 `json:"hoursWorked"`

	// Number of examinations performed
	ExaminationCount int32 `json:"examinationCount"`

	// Number of operations performed
	OperationCount int32 `json:"operationCount"`

	// Number of on-call shifts
	ShiftCount int32 `json:"shiftCount"`

	// Optional free-text note
	Note string `json:"note,omitempty"`
}
