/*
 * Employee Profiles API
 *
 * Employee profiles of hospital staff for the Web-In-Cloud system
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance

import (
	"time"
)

type EmployeeProfile struct {

	// Server-assigned unique identifier
	Id int64 `json:"id,omitempty"`

	FirstName string `json:"firstName"`

	LastName string `json:"lastName"`

	BirthDate string `json:"birthDate"`

	Email string `json:"email,omitempty"`

	Phone string `json:"phone,omitempty"`

	Position string `json:"position"`

	Department string `json:"department,omitempty"`

	Specialization string `json:"specialization"`

	Qualification string `json:"qualification"`

	EmploymentStartDate string `json:"employmentStartDate"`

	Certificates []string `json:"certificates"`

	Note string `json:"note,omitempty"`

	Status EmployeeStatus `json:"status,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty"`

	UpdatedAt time.Time `json:"updatedAt,omitempty"`

	ArchivedAt time.Time `json:"archivedAt,omitempty"`
}
